# -*- coding: utf-8 -*-
"""InputConSqlite.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gKVmLPxjKQsO1COPBf5ud7YRcxb0q0xO
"""
import sqlite3

conn = sqlite3.connect("personas.sqlite")
cursor = conn.cursor()

try:
    cursor.execute("CREATE TABLE personas (nombre TEXT, edad NUMERIC)")
except sqlite3.OperationalError:
  pass

nombre = input("Nombre: ")
edad = int(input("Edad: "))
cursor.execute(f"INSERT INTO personas VALUES ('{nombre}', {edad})")

conn.commit()
print("Datos ingresados correctamente")

conn.close()